services:
  #  backend:
  #    container_name: qb8s.net.${PROJECT_NAME}
  #    image: ${PRIVATE_REGISTRY_URL}/${PROJECT_NAME}:latest
  #    ports:
  #      - "${API_PORT}:8080"
  #    environment:
  #      - ASPNETCORE_ENVIRONMENT=Production
  #      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
  #    depends_on:
  #      - db

  db:
    container_name: qb8s.net.${PROJECT_NAME}-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: qb8s.net.${PROJECT_NAME}-pgadmin
    restart: always
    ports:
      - "8888:80"
    env_file: .env
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db-data: null
  pg-admin-data: null