name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    paths:
      - code/backend/**
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file code/backend/Dockerfile --tag optifit-backend:$(date +%s)
